# Generated by Django 6.0.5 on 2026-05-09 22:31

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluations',
            fields=[
                ('evaluation_id', models.AutoField(primary_key=True, serialize=False)),
                ('score_average', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('evaluation_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'evaluations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Investments',
            fields=[
                ('investment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('withdrawn', 'Withdrawn')], default='pending', max_length=50)),
                ('investment_date', models.DateTimeField(auto_now_add=True)),
                ('roi_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'investments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InvestorRatings',
            fields=[
                ('rating_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(choices=[(1, '1 - Poor'), (2, '2 - Fair'), (3, '3 - Good'), (4, '4 - Very Good'), (5, '5 - Excellent')])),
                ('review', models.TextField(blank=True, null=True)),
                ('rating_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'investor_ratings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, validators=[core.models.validate_no_script])),
                ('image', models.ImageField(upload_to='projects/', validators=[core.models.validate_image])),
                ('description', models.TextField(blank=True, null=True, validators=[core.models.validate_no_script])),
                ('status', models.CharField(choices=[('Investment', 'Investment'), ('Sale', 'Sale'), ('Display', 'Display'), ('Draft', 'Draft')], default='Investment', max_length=50)),
                ('approval_status', models.CharField(choices=[('Draft', 'Draft'), ('Pending Approval', 'Pending Approval'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Draft', max_length=50)),
                ('professor_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('views', models.IntegerField(blank=True, default=0, null=True)),
                ('rank_badge', models.CharField(blank=True, max_length=50, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'projects',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectsMember',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role_in_project', models.CharField(choices=[('owner', 'Owner'), ('member', 'Member')], default='member', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='accepted', max_length=50)),
                ('joined_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'projects_member',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('email', models.EmailField(max_length=255, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('password', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(8)])),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('academic_year', models.IntegerField(blank=True, null=True)),
                ('role', models.CharField(choices=[('student', 'Student'), ('professor', 'Professor'), ('investor', 'Investor')], max_length=50)),
                ('subscription_type', models.CharField(blank=True, max_length=50, null=True)),
                ('linkedin_url', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
